// Package dizi defines generic informtion about Dizi flutes.
package dizi

// Fingering describes the finger positions that produce a note.
type Fingering struct {
	SimpleNotation string
	Fingers        string
	Altis          bool
}

// A map of Dizi key names (e.g. "C", "D", "E", etc.) to their respective note -> fingering position mapping.
var NoteMappings = map[string]map[string]Fingering{
	"C": map[string]Fingering{
		"G4":  {"5̣", "●●● ●●●", false},
		"A4":  {"6̣", "●●● ●●○", false},
		"B4":  {"7̣", "●●● ●○○", false},
		"C5":  {"1", "●●● ○○○", false},
		"D5":  {"2", "●●○ ○○○", false},
		"E5":  {"3", "●○○ ○○○", false},
		"F5":  {"4", "○●● ○○○ : ○●● ○●●", false},
		"F#5": {"_", "○○○ ○○○", false},
		"G5":  {"5", "○●● ●●●", false},
		"A5":  {"6", "●●● ●●○", false},
		"B5":  {"7", "●●● ●○○", false},
		"C6":  {"1̇", "●●● ○○○", false},
		"D6":  {"2̇", "●●○ ○○○", false},
		"E6":  {"3̇", "●○○ ○○○", false},
		"F6":  {"4̇", "○●● ●●○ : ◐○○ ○○○", true},
		"F#6": {"_", "○○○ ●●●", true},
		"G6":  {"5̇", "○●● ●●● : ●●○ ●●○", true},
	},
	"D": map[string]Fingering{
		"A4":  {"5̣", "●●● ●●●", false},
		"B4":  {"6̣", "●●● ●●○", false},
		"C#5": {"7̣", "●●● ●○○", false},
		"D5":  {"1", "●●● ○○○", false},
		"E5":  {"2", "●●○ ○○○", false},
		"F#5": {"3", "●○○ ○○○", false},
		"G5":  {"4", "○●● ○○○ : ○●● ○●●", false},
		"G#5": {"_", "○○○ ○○○", false},
		"A5":  {"5", "○●● ●●●", false},
		"B5":  {"6", "●●● ●●○", false},
		"C#6": {"7", "●●● ●○○", false},
		"D6":  {"1̇", "●●● ○○○", false},
		"E6":  {"2̇", "●●○ ○○○", false},
		"F#6": {"3̇", "●○○ ○○○", false},
		"G6":  {"4̇", "○●● ●●○ : ◐○○ ○○○", true},
		"G#6": {"_", "○○○ ●●●", true},
		"A6":  {"5̇", "○●● ●●● : ●●○ ●●○", true},
	},
	"E": map[string]Fingering{
		"B4":  {"5̣", "●●● ●●●", false},
		"C#5": {"6̣", "●●● ●●○", false},
		"D#5": {"7̣", "●●● ●○○", false},
		"E5":  {"1", "●●● ○○○", false},
		"F#5": {"2", "●●○ ○○○", false},
		"G#5": {"3", "●○○ ○○○", false},
		"A5":  {"4", "○●● ○○○ : ○●● ○●●", false},
		"A#5": {"_", "○○○ ○○○", false},
		"B5":  {"5", "○●● ●●●", false},
		"C#6": {"6", "●●● ●●○", false},
		"D#6": {"7", "●●● ●○○", false},
		"E6":  {"1̇", "●●● ○○○", false},
		"F#6": {"2̇", "●●○ ○○○", false},
		"G#6": {"3̇", "●○○ ○○○", false},
		"A6":  {"4̇", "○●● ●●○ : ◐○○ ○○○", true},
		"A#6": {"_", "○○○ ●●●", true},
		"B6":  {"5̇", "○●● ●●● : ●●○ ●●○", true},
	},
	"F": map[string]Fingering{
		"C5":  {"5̣", "●●● ●●●", false},
		"D5":  {"6̣", "●●● ●●○", false},
		"E5":  {"7̣", "●●● ●○○", false},
		"F5":  {"1", "●●● ○○○", false},
		"G5":  {"2", "●●○ ○○○", false},
		"A5":  {"3", "●○○ ○○○", false},
		"A#5": {"4", "○●● ○○○ : ○●● ○●●", false},
		"B5":  {"_", "○○○ ○○○", false},
		"C6":  {"5", "○●● ●●●", false},
		"D6":  {"6", "●●● ●●○", false},
		"E6":  {"7", "●●● ●○○", false},
		"F6":  {"1̇", "●●● ○○○", false},
		"G6":  {"2̇", "●●○ ○○○", false},
		"A6":  {"3̇", "●○○ ○○○", false},
		"A#6": {"4̇", "○●● ●●○ : ◐○○ ○○○", true},
		"B6":  {"_", "○○○ ●●●", true},
		"C7":  {"5̇", "○●● ●●● : ●●○ ●●○", true},
	},
	"G": map[string]Fingering{
		"D5":  {"5̣", "●●● ●●●", false},
		"E5":  {"6̣", "●●● ●●○", false},
		"E#5": {"7̣", "●●● ●○○", false},
		"G5":  {"1", "●●● ○○○", false},
		"A5":  {"2", "●●○ ○○○", false},
		"B5":  {"3", "●○○ ○○○", false},
		"C6":  {"4", "○●● ○○○ : ○●● ○●●", false},
		"C#6": {"_", "○○○ ○○○", false},
		"D6":  {"5", "○●● ●●●", false},
		"E6":  {"6", "●●● ●●○", false},
		"F#6": {"7", "●●● ●○○", false},
		"G6":  {"1̇", "●●● ○○○", false},
		"A6":  {"2̇", "●●○ ○○○", false},
		"B6":  {"3̇", "●○○ ○○○", false},
		"C7":  {"4̇", "○●● ●●○ : ◐○○ ○○○", true},
		"C#7": {"_", "○○○ ●●●", true},
		"D7":  {"5̇", "○●● ●●● : ●●○ ●●○", true},
	},
}
